apiVersion: v1
kind: Secret
metadata:
  name: metro-server-secret
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  DB_USER: {{ .Values.db.user | quote }}
  DB_PASSWORD: {{ .Values.db.password | quote }}
