apiVersion: v1
kind: Service
metadata:
  name: metro-server
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  type: {{ if .Values.debug.enabled }}NodePort{{ else }}ClusterIP{{ end }}
  selector:
    app: metro-server
  ports:
    - name: app
      port: 3000
      targetPort: 3000
  {{- if .Values.debug.enabled }}
    - name: debug
      port: {{ .Values.debug.port }}
      targetPort: {{ .Values.debug.port }}
      nodePort: {{ .Values.debug.nodePort }}
      protocol: TCP
  {{- end }}
