apiVersion: apps/v1
kind: Deployment
metadata:
  name: metro-web
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: metro-web
  template:
    metadata:
      labels:
        app: metro-web
    spec:
      containers:
        - name: web
          image: "{{ .Values.dev.image }}"
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "npm install && npm run dev -- --host 0.0.0.0"]
          workingDir: /app
          ports:
            - containerPort: 5173
          volumeMounts:
            - name: source
              mountPath: /app
#            - name: node-modules
#              mountPath: /app/node_modules
      volumes:
        - name: source
          hostPath:
            path: {{ .Values.dev.hostPath }}
#        - name: node-modules
#          hostPath:
#            path: {{ .Values.dev.hostPath }}/node_modules
