apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metro-web-ingress
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.domain.web }}
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: metro-server
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: metro-web
                port:
                  number: 5173
