apiVersion: v1
kind: Service
metadata:
  name: metro-web
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  selector:
    app: metro-web
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: ClusterIP
