import type { Knex } from 'knex';

const rows = [
  // R line
  { line_code: 'R', route_id: 'R-1', service_day: '平日', peak_flag: 0, start_time: '06:00', end_time: '07:00', min_headway_min: 8, max_headway_min: 10 },
  { line_code: 'R', route_id: 'R-1', service_day: '平日', peak_flag: 1, start_time: '07:00', end_time: '09:00', min_headway_min: 6, max_headway_min: 6 },
  { line_code: 'R', route_id: 'R-1', service_day: '平日', peak_flag: 0, start_time: '09:00', end_time: '17:00', min_headway_min: 8, max_headway_min: 10 },
  { line_code: 'R', route_id: 'R-1', service_day: '平日', peak_flag: 1, start_time: '17:00', end_time: '19:30', min_headway_min: 6, max_headway_min: 6 },
  { line_code: 'R', route_id: 'R-1', service_day: '平日', peak_flag: 0, start_time: '19:30', end_time: '23:00', min_headway_min: 8, max_headway_min: 10 },
  { line_code: 'R', route_id: 'R-1', service_day: '平日', peak_flag: 0, start_time: '23:00', end_time: '00:00', min_headway_min: 12, max_headway_min: 12 },
  { line_code: 'R', route_id: 'R-1', service_day: '假日', peak_flag: 0, start_time: '06:00', end_time: '23:00', min_headway_min: 8, max_headway_min: 10 },
  { line_code: 'R', route_id: 'R-1', service_day: '假日', peak_flag: 0, start_time: '23:00', end_time: '00:00', min_headway_min: 12, max_headway_min: 12 },
  { line_code: 'R', route_id: 'R-2', service_day: '平日', peak_flag: 0, start_time: '06:00', end_time: '07:00', min_headway_min: 8, max_headway_min: 10 },
  { line_code: 'R', route_id: 'R-2', service_day: '平日', peak_flag: 1, start_time: '07:00', end_time: '09:00', min_headway_min: 6, max_headway_min: 6 },
  { line_code: 'R', route_id: 'R-2', service_day: '平日', peak_flag: 0, start_time: '09:00', end_time: '17:00', min_headway_min: 8, max_headway_min: 10 },
  { line_code: 'R', route_id: 'R-2', service_day: '平日', peak_flag: 1, start_time: '17:00', end_time: '19:30', min_headway_min: 6, max_headway_min: 6 },
  { line_code: 'R', route_id: 'R-2', service_day: '平日', peak_flag: 0, start_time: '19:30', end_time: '23:00', min_headway_min: 8, max_headway_min: 10 },
  { line_code: 'R', route_id: 'R-2', service_day: '假日', peak_flag: 0, start_time: '08:00', end_time: '23:00', min_headway_min: 8, max_headway_min: 10 },
  { line_code: 'R', route_id: 'R-3', service_day: '平日', peak_flag: 0, start_time: '06:00', end_time: '06:30', min_headway_min: 12, max_headway_min: 15 },
  { line_code: 'R', route_id: 'R-3', service_day: '平日', peak_flag: 1, start_time: '06:30', end_time: '09:00', min_headway_min: 7, max_headway_min: 8 },
  { line_code: 'R', route_id: 'R-3', service_day: '平日', peak_flag: 0, start_time: '09:00', end_time: '17:00', min_headway_min: 10, max_headway_min: 10 },
  { line_code: 'R', route_id: 'R-3', service_day: '平日', peak_flag: 1, start_time: '17:00', end_time: '19:30', min_headway_min: 7, max_headway_min: 8 },
  { line_code: 'R', route_id: 'R-3', service_day: '平日', peak_flag: 0, start_time: '19:30', end_time: '23:00', min_headway_min: 8, max_headway_min: 10 },
  { line_code: 'R', route_id: 'R-3', service_day: '平日', peak_flag: 0, start_time: '23:00', end_time: '00:00', min_headway_min: 12, max_headway_min: 15 },
  { line_code: 'R', route_id: 'R-3', service_day: '假日', peak_flag: 0, start_time: '06:00', end_time: '23:00', min_headway_min: 10, max_headway_min: 12 },
  { line_code: 'R', route_id: 'R-3', service_day: '假日', peak_flag: 0, start_time: '23:00', end_time: '00:00', min_headway_min: 12, max_headway_min: 15 },
  // BL line
  { line_code: 'BL', route_id: 'BL-1', service_day: '平日', peak_flag: 0, start_time: '06:00', end_time: '07:00', min_headway_min: 8, max_headway_min: 10 },
  { line_code: 'BL', route_id: 'BL-1', service_day: '平日', peak_flag: 1, start_time: '07:00', end_time: '09:00', min_headway_min: 6, max_headway_min: 6 },
  { line_code: 'BL', route_id: 'BL-1', service_day: '平日', peak_flag: 0, start_time: '09:00', end_time: '17:00', min_headway_min: 8, max_headway_min: 10 },
  { line_code: 'BL', route_id: 'BL-1', service_day: '平日', peak_flag: 1, start_time: '17:00', end_time: '19:30', min_headway_min: 6, max_headway_min: 6 },
  { line_code: 'BL', route_id: 'BL-1', service_day: '平日', peak_flag: 0, start_time: '19:30', end_time: '23:00', min_headway_min: 8, max_headway_min: 10 },
  { line_code: 'BL', route_id: 'BL-1', service_day: '平日', peak_flag: 0, start_time: '23:00', end_time: '00:00', min_headway_min: 8, max_headway_min: 12 },
  { line_code: 'BL', route_id: 'BL-1', service_day: '假日', peak_flag: 0, start_time: '06:00', end_time: '23:00', min_headway_min: 8, max_headway_min: 10 },
  { line_code: 'BL', route_id: 'BL-1', service_day: '假日', peak_flag: 0, start_time: '23:00', end_time: '00:00', min_headway_min: 8, max_headway_min: 12 },
  { line_code: 'BL', route_id: 'BL-2', service_day: '平日', peak_flag: 0, start_time: '06:00', end_time: '07:00', min_headway_min: 8, max_headway_min: 10 },
  { line_code: 'BL', route_id: 'BL-2', service_day: '平日', peak_flag: 1, start_time: '07:00', end_time: '09:00', min_headway_min: 6, max_headway_min: 6 },
  { line_code: 'BL', route_id: 'BL-2', service_day: '平日', peak_flag: 0, start_time: '09:00', end_time: '17:00', min_headway_min: 8, max_headway_min: 10 },
  { line_code: 'BL', route_id: 'BL-2', service_day: '平日', peak_flag: 1, start_time: '17:00', end_time: '19:30', min_headway_min: 6, max_headway_min: 6 },
  { line_code: 'BL', route_id: 'BL-2', service_day: '平日', peak_flag: 0, start_time: '19:30', end_time: '23:00', min_headway_min: 8, max_headway_min: 10 },
  { line_code: 'BL', route_id: 'BL-2', service_day: '假日', peak_flag: 0, start_time: '08:00', end_time: '23:00', min_headway_min: 8, max_headway_min: 10 },
  // BR line
  { line_code: 'BR', route_id: 'BR-1', service_day: '平日', peak_flag: 0, start_time: '06:00', end_time: '07:00', min_headway_min: 4, max_headway_min: 10 },
  { line_code: 'BR', route_id: 'BR-1', service_day: '平日', peak_flag: 1, start_time: '07:00', end_time: '09:00', min_headway_min: 2, max_headway_min: 4 },
  { line_code: 'BR', route_id: 'BR-1', service_day: '平日', peak_flag: 0, start_time: '09:00', end_time: '17:00', min_headway_min: 4, max_headway_min: 10 },
  { line_code: 'BR', route_id: 'BR-1', service_day: '平日', peak_flag: 1, start_time: '17:00', end_time: '19:30', min_headway_min: 2, max_headway_min: 4 },
  { line_code: 'BR', route_id: 'BR-1', service_day: '平日', peak_flag: 0, start_time: '19:30', end_time: '23:00', min_headway_min: 4, max_headway_min: 10 },
  { line_code: 'BR', route_id: 'BR-1', service_day: '平日', peak_flag: 0, start_time: '23:00', end_time: '00:00', min_headway_min: 12, max_headway_min: 12 },
  { line_code: 'BR', route_id: 'BR-1', service_day: '假日', peak_flag: 0, start_time: '06:00', end_time: '23:00', min_headway_min: 4, max_headway_min: 10 },
  { line_code: 'BR', route_id: 'BR-1', service_day: '假日', peak_flag: 0, start_time: '23:00', end_time: '00:00', min_headway_min: 12, max_headway_min: 12 },
  // G line
  { line_code: 'G', route_id: 'G-1', service_day: '平日', peak_flag: 0, start_time: '06:00', end_time: '07:00', min_headway_min: 6, max_headway_min: 8 },
  { line_code: 'G', route_id: 'G-1', service_day: '平日', peak_flag: 1, start_time: '07:00', end_time: '09:00', min_headway_min: 4, max_headway_min: 6 },
  { line_code: 'G', route_id: 'G-1', service_day: '平日', peak_flag: 0, start_time: '09:00', end_time: '17:00', min_headway_min: 6, max_headway_min: 8 },
  { line_code: 'G', route_id: 'G-1', service_day: '平日', peak_flag: 1, start_time: '17:00', end_time: '19:30', min_headway_min: 4, max_headway_min: 6 },
  { line_code: 'G', route_id: 'G-1', service_day: '平日', peak_flag: 0, start_time: '19:30', end_time: '23:00', min_headway_min: 6, max_headway_min: 8 },
  { line_code: 'G', route_id: 'G-1', service_day: '平日', peak_flag: 0, start_time: '23:00', end_time: '00:00', min_headway_min: 12, max_headway_min: 12 },
  { line_code: 'G', route_id: 'G-1', service_day: '假日', peak_flag: 0, start_time: '06:00', end_time: '09:00', min_headway_min: 8, max_headway_min: 10 },
  { line_code: 'G', route_id: 'G-1', service_day: '假日', peak_flag: 0, start_time: '09:00', end_time: '23:00', min_headway_min: 6, max_headway_min: 8 },
  { line_code: 'G', route_id: 'G-1', service_day: '假日', peak_flag: 0, start_time: '23:00', end_time: '00:00', min_headway_min: 12, max_headway_min: 12 },
  { line_code: 'G', route_id: 'G-2', service_day: '平日', peak_flag: 1, start_time: '07:00', end_time: '09:00', min_headway_min: 4, max_headway_min: 6 },
  { line_code: 'G', route_id: 'G-2', service_day: '平日', peak_flag: 1, start_time: '17:00', end_time: '19:30', min_headway_min: 4, max_headway_min: 6 },
  { line_code: 'G', route_id: 'G-3', service_day: '平日', peak_flag: 0, start_time: '06:00', end_time: '00:00', min_headway_min: 12, max_headway_min: 20 },
  { line_code: 'G', route_id: 'G-3', service_day: '假日', peak_flag: 0, start_time: '06:00', end_time: '00:00', min_headway_min: 12, max_headway_min: 20 },
  // O line
  { line_code: 'O', route_id: 'O-1', service_day: '平日', peak_flag: 0, start_time: '06:00', end_time: '07:00', min_headway_min: 9, max_headway_min: 10 },
  { line_code: 'O', route_id: 'O-1', service_day: '平日', peak_flag: 1, start_time: '07:00', end_time: '09:00', min_headway_min: 6, max_headway_min: 6 },
  { line_code: 'O', route_id: 'O-1', service_day: '平日', peak_flag: 0, start_time: '09:00', end_time: '17:00', min_headway_min: 9, max_headway_min: 10 },
  { line_code: 'O', route_id: 'O-1', service_day: '平日', peak_flag: 1, start_time: '17:00', end_time: '19:30', min_headway_min: 6, max_headway_min: 6 },
  { line_code: 'O', route_id: 'O-1', service_day: '平日', peak_flag: 0, start_time: '19:30', end_time: '23:00', min_headway_min: 9, max_headway_min: 10 },
  { line_code: 'O', route_id: 'O-1', service_day: '平日', peak_flag: 0, start_time: '23:00', end_time: '00:00', min_headway_min: 12, max_headway_min: 12 },
  { line_code: 'O', route_id: 'O-1', service_day: '假日', peak_flag: 0, start_time: '06:00', end_time: '23:00', min_headway_min: 9, max_headway_min: 10 },
  { line_code: 'O', route_id: 'O-1', service_day: '假日', peak_flag: 0, start_time: '23:00', end_time: '00:00', min_headway_min: 12, max_headway_min: 12 },
  { line_code: 'O', route_id: 'O-2', service_day: '平日', peak_flag: 0, start_time: '06:00', end_time: '07:00', min_headway_min: 9, max_headway_min: 10 },
  { line_code: 'O', route_id: 'O-2', service_day: '平日', peak_flag: 1, start_time: '07:00', end_time: '09:00', min_headway_min: 6, max_headway_min: 6 },
  { line_code: 'O', route_id: 'O-2', service_day: '平日', peak_flag: 0, start_time: '09:00', end_time: '17:00', min_headway_min: 9, max_headway_min: 10 },
  { line_code: 'O', route_id: 'O-2', service_day: '平日', peak_flag: 1, start_time: '17:00', end_time: '19:30', min_headway_min: 6, max_headway_min: 6 },
  { line_code: 'O', route_id: 'O-2', service_day: '平日', peak_flag: 0, start_time: '19:30', end_time: '23:00', min_headway_min: 9, max_headway_min: 10 },
  { line_code: 'O', route_id: 'O-2', service_day: '平日', peak_flag: 0, start_time: '23:00', end_time: '00:00', min_headway_min: 12, max_headway_min: 12 },
  { line_code: 'O', route_id: 'O-2', service_day: '假日', peak_flag: 0, start_time: '06:00', end_time: '23:00', min_headway_min: 9, max_headway_min: 10 },
  { line_code: 'O', route_id: 'O-2', service_day: '假日', peak_flag: 0, start_time: '23:00', end_time: '00:00', min_headway_min: 12, max_headway_min: 12 },
  // Y line
  { line_code: 'Y', route_id: 'Y-1', service_day: '平日', peak_flag: 0, start_time: '06:00', end_time: '07:00', min_headway_min: 5, max_headway_min: 10 },
  { line_code: 'Y', route_id: 'Y-1', service_day: '平日', peak_flag: 1, start_time: '07:00', end_time: '09:00', min_headway_min: 4, max_headway_min: 7 },
  { line_code: 'Y', route_id: 'Y-1', service_day: '平日', peak_flag: 0, start_time: '09:00', end_time: '17:00', min_headway_min: 5, max_headway_min: 10 },
  { line_code: 'Y', route_id: 'Y-1', service_day: '平日', peak_flag: 1, start_time: '17:00', end_time: '19:30', min_headway_min: 4, max_headway_min: 7 },
  { line_code: 'Y', route_id: 'Y-1', service_day: '平日', peak_flag: 0, start_time: '19:30', end_time: '23:00', min_headway_min: 5, max_headway_min: 10 },
  { line_code: 'Y', route_id: 'Y-1', service_day: '平日', peak_flag: 0, start_time: '23:00', end_time: '00:00', min_headway_min: 12, max_headway_min: 15 },
  { line_code: 'Y', route_id: 'Y-1', service_day: '假日', peak_flag: 0, start_time: '06:00', end_time: '23:00', min_headway_min: 5, max_headway_min: 10 },
  { line_code: 'Y', route_id: 'Y-1', service_day: '假日', peak_flag: 0, start_time: '23:00', end_time: '00:00', min_headway_min: 12, max_headway_min: 15 },
];

export async function seed(knex: Knex): Promise<void> {
  await knex('route_headways').del();
  await knex('route_headways').insert(rows);
}

