import type { Knex } from 'knex';

const rows: { line_code: string; from_station_code: string; to_station_code: string; travel_time_min: number }[] = [
  // 文湖線 BR
  { line_code: 'BR', from_station_code: 'BR01', to_station_code: 'BR02', travel_time_min: 2 },
  { line_code: 'BR', from_station_code: 'BR02', to_station_code: 'BR03', travel_time_min: 1 },
  { line_code: 'BR', from_station_code: 'BR03', to_station_code: 'BR04', travel_time_min: 2 },
  { line_code: 'BR', from_station_code: 'BR04', to_station_code: 'BR05', travel_time_min: 2 },
  { line_code: 'BR', from_station_code: 'BR05', to_station_code: 'BR06', travel_time_min: 3 },
  { line_code: 'BR', from_station_code: 'BR06', to_station_code: 'BR07', travel_time_min: 2 },
  { line_code: 'BR', from_station_code: 'BR07', to_station_code: 'BR08', travel_time_min: 3 },
  { line_code: 'BR', from_station_code: 'BR08', to_station_code: 'BR09', travel_time_min: 2 },
  { line_code: 'BR', from_station_code: 'BR09', to_station_code: 'BR10', travel_time_min: 2 },
  { line_code: 'BR', from_station_code: 'BR10', to_station_code: 'BR11', travel_time_min: 2 },
  { line_code: 'BR', from_station_code: 'BR11', to_station_code: 'BR12', travel_time_min: 2 },
  { line_code: 'BR', from_station_code: 'BR12', to_station_code: 'BR13', travel_time_min: 3 },
  { line_code: 'BR', from_station_code: 'BR13', to_station_code: 'BR14', travel_time_min: 3 },
  { line_code: 'BR', from_station_code: 'BR14', to_station_code: 'BR15', travel_time_min: 2 },
  { line_code: 'BR', from_station_code: 'BR15', to_station_code: 'BR16', travel_time_min: 2 },
  { line_code: 'BR', from_station_code: 'BR16', to_station_code: 'BR17', travel_time_min: 2 },
  { line_code: 'BR', from_station_code: 'BR17', to_station_code: 'BR18', travel_time_min: 2 },
  { line_code: 'BR', from_station_code: 'BR18', to_station_code: 'BR19', travel_time_min: 2 },
  { line_code: 'BR', from_station_code: 'BR19', to_station_code: 'BR20', travel_time_min: 2 },
  { line_code: 'BR', from_station_code: 'BR20', to_station_code: 'BR21', travel_time_min: 3 },
  { line_code: 'BR', from_station_code: 'BR21', to_station_code: 'BR22', travel_time_min: 2 },
  { line_code: 'BR', from_station_code: 'BR22', to_station_code: 'BR23', travel_time_min: 2 },
  { line_code: 'BR', from_station_code: 'BR23', to_station_code: 'BR24', travel_time_min: 2 },
  // 板南線 BL
  { line_code: 'BL', from_station_code: 'BL01', to_station_code: 'BL02', travel_time_min: 3 },
  { line_code: 'BL', from_station_code: 'BL02', to_station_code: 'BL03', travel_time_min: 2 },
  { line_code: 'BL', from_station_code: 'BL03', to_station_code: 'BL04', travel_time_min: 2 },
  { line_code: 'BL', from_station_code: 'BL04', to_station_code: 'BL05', travel_time_min: 3 },
  { line_code: 'BL', from_station_code: 'BL05', to_station_code: 'BL06', travel_time_min: 2 },
  { line_code: 'BL', from_station_code: 'BL06', to_station_code: 'BL07', travel_time_min: 2 },
  { line_code: 'BL', from_station_code: 'BL07', to_station_code: 'BL08', travel_time_min: 2 },
  { line_code: 'BL', from_station_code: 'BL08', to_station_code: 'BL09', travel_time_min: 2 },
  { line_code: 'BL', from_station_code: 'BL09', to_station_code: 'BL10', travel_time_min: 4 },
  { line_code: 'BL', from_station_code: 'BL10', to_station_code: 'BL11', travel_time_min: 2 },
  { line_code: 'BL', from_station_code: 'BL11', to_station_code: 'BL12', travel_time_min: 2 },
  { line_code: 'BL', from_station_code: 'BL12', to_station_code: 'BL13', travel_time_min: 2 },
  { line_code: 'BL', from_station_code: 'BL13', to_station_code: 'BL14', travel_time_min: 2 },
  { line_code: 'BL', from_station_code: 'BL14', to_station_code: 'BL15', travel_time_min: 2 },
  { line_code: 'BL', from_station_code: 'BL15', to_station_code: 'BL16', travel_time_min: 2 },
  { line_code: 'BL', from_station_code: 'BL16', to_station_code: 'BL17', travel_time_min: 2 },
  { line_code: 'BL', from_station_code: 'BL17', to_station_code: 'BL18', travel_time_min: 2 },
  { line_code: 'BL', from_station_code: 'BL18', to_station_code: 'BL19', travel_time_min: 2 },
  { line_code: 'BL', from_station_code: 'BL19', to_station_code: 'BL20', travel_time_min: 2 },
  { line_code: 'BL', from_station_code: 'BL20', to_station_code: 'BL21', travel_time_min: 2 },
  { line_code: 'BL', from_station_code: 'BL21', to_station_code: 'BL22', travel_time_min: 2 },
  { line_code: 'BL', from_station_code: 'BL22', to_station_code: 'BL23', travel_time_min: 2 },
  // 松山新店線 G（主線 + 小碧潭支線）
  { line_code: 'G', from_station_code: 'G01',  to_station_code: 'G02',  travel_time_min: 2 },
  { line_code: 'G', from_station_code: 'G02',  to_station_code: 'G03',  travel_time_min: 2 },
  { line_code: 'G', from_station_code: 'G03',  to_station_code: 'G03A', travel_time_min: 4 },
  { line_code: 'G', from_station_code: 'G03A', to_station_code: 'G04',  travel_time_min: 8 },
  { line_code: 'G', from_station_code: 'G04',  to_station_code: 'G05',  travel_time_min: 2 },
  { line_code: 'G', from_station_code: 'G05',  to_station_code: 'G06',  travel_time_min: 2 },
  { line_code: 'G', from_station_code: 'G06',  to_station_code: 'G07',  travel_time_min: 3 },
  { line_code: 'G', from_station_code: 'G07',  to_station_code: 'G08',  travel_time_min: 2 },
  { line_code: 'G', from_station_code: 'G08',  to_station_code: 'G09',  travel_time_min: 2 },
  { line_code: 'G', from_station_code: 'G09',  to_station_code: 'G10',  travel_time_min: 2 },
  { line_code: 'G', from_station_code: 'G10',  to_station_code: 'G11',  travel_time_min: 2 },
  { line_code: 'G', from_station_code: 'G11',  to_station_code: 'G12',  travel_time_min: 2 },
  { line_code: 'G', from_station_code: 'G12',  to_station_code: 'G13',  travel_time_min: 2 },
  { line_code: 'G', from_station_code: 'G13',  to_station_code: 'G14',  travel_time_min: 2 },
  { line_code: 'G', from_station_code: 'G14',  to_station_code: 'G15',  travel_time_min: 2 },
  { line_code: 'G', from_station_code: 'G15',  to_station_code: 'G16',  travel_time_min: 2 },
  { line_code: 'G', from_station_code: 'G16',  to_station_code: 'G17',  travel_time_min: 2 },
  { line_code: 'G', from_station_code: 'G17',  to_station_code: 'G18',  travel_time_min: 2 },
  { line_code: 'G', from_station_code: 'G18',  to_station_code: 'G19',  travel_time_min: 3 },
  // 中和新蘆線 O（主線 + 蘆洲支線）
  { line_code: 'O', from_station_code: 'O01',  to_station_code: 'O02',  travel_time_min: 2 },
  { line_code: 'O', from_station_code: 'O02',  to_station_code: 'O03',  travel_time_min: 2 },
  { line_code: 'O', from_station_code: 'O03',  to_station_code: 'O04',  travel_time_min: 2 },
  { line_code: 'O', from_station_code: 'O04',  to_station_code: 'O05',  travel_time_min: 4 },
  { line_code: 'O', from_station_code: 'O05',  to_station_code: 'O06',  travel_time_min: 4 },
  { line_code: 'O', from_station_code: 'O06',  to_station_code: 'O07',  travel_time_min: 3 },
  { line_code: 'O', from_station_code: 'O07',  to_station_code: 'O08',  travel_time_min: 2 },
  { line_code: 'O', from_station_code: 'O08',  to_station_code: 'O09',  travel_time_min: 2 },
  { line_code: 'O', from_station_code: 'O09',  to_station_code: 'O10',  travel_time_min: 2 },
  { line_code: 'O', from_station_code: 'O10',  to_station_code: 'O11',  travel_time_min: 2 },
  { line_code: 'O', from_station_code: 'O11',  to_station_code: 'O12',  travel_time_min: 2 },
  { line_code: 'O', from_station_code: 'O12',  to_station_code: 'O13',  travel_time_min: 3 },
  { line_code: 'O', from_station_code: 'O13',  to_station_code: 'O14',  travel_time_min: 2 },
  { line_code: 'O', from_station_code: 'O14',  to_station_code: 'O15',  travel_time_min: 2 },
  { line_code: 'O', from_station_code: 'O15',  to_station_code: 'O16',  travel_time_min: 3 },
  { line_code: 'O', from_station_code: 'O16',  to_station_code: 'O17',  travel_time_min: 2 },
  { line_code: 'O', from_station_code: 'O17',  to_station_code: 'O18',  travel_time_min: 2 },
  { line_code: 'O', from_station_code: 'O18',  to_station_code: 'O19',  travel_time_min: 3 },
  { line_code: 'O', from_station_code: 'O19',  to_station_code: 'O20',  travel_time_min: 2 },
  { line_code: 'O', from_station_code: 'O20',  to_station_code: 'O21',  travel_time_min: 3 },
  { line_code: 'O', from_station_code: 'O50',  to_station_code: 'O51',  travel_time_min: 2 },
  { line_code: 'O', from_station_code: 'O51',  to_station_code: 'O52',  travel_time_min: 2 },
  { line_code: 'O', from_station_code: 'O52',  to_station_code: 'O53',  travel_time_min: 2 },
  { line_code: 'O', from_station_code: 'O53',  to_station_code: 'O54',  travel_time_min: 2 },
  // 淡水信義線 R（主線 + 新北投支線）
  { line_code: 'R', from_station_code: 'R02',  to_station_code: 'R03',  travel_time_min: 2 },
  { line_code: 'R', from_station_code: 'R03',  to_station_code: 'R04',  travel_time_min: 2 },
  { line_code: 'R', from_station_code: 'R04',  to_station_code: 'R05',  travel_time_min: 2 },
  { line_code: 'R', from_station_code: 'R05',  to_station_code: 'R06',  travel_time_min: 2 },
  { line_code: 'R', from_station_code: 'R06',  to_station_code: 'R07',  travel_time_min: 2 },
  { line_code: 'R', from_station_code: 'R07',  to_station_code: 'R08',  travel_time_min: 3 },
  { line_code: 'R', from_station_code: 'R08',  to_station_code: 'R09',  travel_time_min: 2 },
  { line_code: 'R', from_station_code: 'R09',  to_station_code: 'R10',  travel_time_min: 2 },
  { line_code: 'R', from_station_code: 'R10',  to_station_code: 'R11',  travel_time_min: 2 },
  { line_code: 'R', from_station_code: 'R11',  to_station_code: 'R12',  travel_time_min: 2 },
  { line_code: 'R', from_station_code: 'R12',  to_station_code: 'R13',  travel_time_min: 1 },
  { line_code: 'R', from_station_code: 'R13',  to_station_code: 'R14',  travel_time_min: 2 },
  { line_code: 'R', from_station_code: 'R14',  to_station_code: 'R15',  travel_time_min: 2 },
  { line_code: 'R', from_station_code: 'R15',  to_station_code: 'R16',  travel_time_min: 2 },
  { line_code: 'R', from_station_code: 'R16',  to_station_code: 'R17',  travel_time_min: 2 },
  { line_code: 'R', from_station_code: 'R17',  to_station_code: 'R18',  travel_time_min: 2 },
  { line_code: 'R', from_station_code: 'R18',  to_station_code: 'R19',  travel_time_min: 2 },
  { line_code: 'R', from_station_code: 'R19',  to_station_code: 'R20',  travel_time_min: 2 },
  { line_code: 'R', from_station_code: 'R20',  to_station_code: 'R21',  travel_time_min: 2 },
  { line_code: 'R', from_station_code: 'R21',  to_station_code: 'R22',  travel_time_min: 2 },
  { line_code: 'R', from_station_code: 'R22',  to_station_code: 'R22A', travel_time_min: 3 },
  { line_code: 'R', from_station_code: 'R22A', to_station_code: 'R23',  travel_time_min: 8 },
  { line_code: 'R', from_station_code: 'R23',  to_station_code: 'R24',  travel_time_min: 2 },
  { line_code: 'R', from_station_code: 'R24',  to_station_code: 'R25',  travel_time_min: 2 },
  { line_code: 'R', from_station_code: 'R25',  to_station_code: 'R26',  travel_time_min: 3 },
  { line_code: 'R', from_station_code: 'R26',  to_station_code: 'R27',  travel_time_min: 3 },
  { line_code: 'R', from_station_code: 'R27',  to_station_code: 'R28',  travel_time_min: 3 },
  // 環狀線 Y
  { line_code: 'Y', from_station_code: 'Y07',  to_station_code: 'Y08',  travel_time_min: 3 },
  { line_code: 'Y', from_station_code: 'Y08',  to_station_code: 'Y09',  travel_time_min: 2 },
  { line_code: 'Y', from_station_code: 'Y09',  to_station_code: 'Y10',  travel_time_min: 2 },
  { line_code: 'Y', from_station_code: 'Y10',  to_station_code: 'Y11',  travel_time_min: 2 },
  { line_code: 'Y', from_station_code: 'Y11',  to_station_code: 'Y12',  travel_time_min: 4 },
  { line_code: 'Y', from_station_code: 'Y12',  to_station_code: 'Y13',  travel_time_min: 2 },
  { line_code: 'Y', from_station_code: 'Y13',  to_station_code: 'Y14',  travel_time_min: 2 },
  { line_code: 'Y', from_station_code: 'Y14',  to_station_code: 'Y15',  travel_time_min: 2 },
  { line_code: 'Y', from_station_code: 'Y15',  to_station_code: 'Y16',  travel_time_min: 3 },
  { line_code: 'Y', from_station_code: 'Y16',  to_station_code: 'Y17',  travel_time_min: 4 },
  { line_code: 'Y', from_station_code: 'Y17',  to_station_code: 'Y18',  travel_time_min: 3 },
  { line_code: 'Y', from_station_code: 'Y18',  to_station_code: 'Y19',  travel_time_min: 2 },
  { line_code: 'Y', from_station_code: 'Y19',  to_station_code: 'Y20',  travel_time_min: 3 },
];

export async function seed(knex: Knex): Promise<void> {
  await knex('station_segment_times').del();
  await knex('station_segment_times').insert(rows);
}

